name: Deploy AntCatalog to Azure App Service

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: antcatalog

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/hydrogen

      - name: npm ci and build on /client
        run: |
          npm ci
          npm run build
        working-directory: client

      - name: npm ci, test, and build on /server
        run: |
          npm ci
          npm run test
          npm run build
        working-directory: server

      - name: Prepare Deployment Assets
        run: |
          rm -r ./logs
          mv ../client/build ./public
        working-directory: server

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: './server'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
