name: Deploy AntCatalog to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: antcatalog
  NODE_VERSION: 'lts/hydrogen'

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@main

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: npm install and build on /client
        run: |
          npm install
          npm run build
        working-directory: client

      - name: npm install, test, and build on /server
        run: |
          npm install
          npm run test
          mv ../client/build ./public
          npm run build
        working-directory: server

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: './server'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
