name: Poll to Keep AntCatalog Active

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  poll:
    name: Poll
    runs-on: ubuntu-20.04
    timeout-minutes: 1
    steps:
      - name: Send a Request to the API
        run: |
          curl https://antcatalog.azurewebsites.net/instructors?name=random_name -m 5
